import type { Metadata } from "next";
import { Merriweather_Sans, Inter } from "next/font/google";
import "./globals.css";
import MyAppProvider from "@/providers";

const gamee = Merriweather_Sans({
  variable: "--font-gamee",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "GAMEES!!!",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <MyAppProvider>{children}</MyAppProvider>
      </body>
    </html>
  );
}
