import type {Metadata} from "next";
import {Merriweather_Sans} from "next/font/google";
import "./globals.css";

const gamee = Merriweather_Sans(
    {
        variable: '--font-gamee',
        subsets: ["latin"]
    }
);
// const resolve =

export const metadata: Metadata = {
    title: "GAMEES!!!",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;

}>) {


    return (
        <html lang="en" className={`${gamee.variable} font-sans`}>
        <body>
        {children}
        </body>

        </html>
    );
}


